"""
Django settings for boke project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k*3#gi97)0g$6&pob2+g#bl8)+z@hg!a1u6^78nbw#k5t9tg+b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'firstApp',
	'tinymce'
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'firstApp.middlewares.verifycodeMiddlewares.VerifycodeMiddlewares',
	'firstApp.middlewares.loginMiddlewares.LoginMiddlewares',
]

ROOT_URLCONF = 'times.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'times.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
# mysql配置
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'qshdata',
		'USER': 'root',
		'PASSWORD': '199652',
		'HOST': '39.96.13.213',
		'PORT': 3306,

	}
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# 静态文件
STATIC_URL = '/static/'
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, 'statics')
]

#算法路径
ARITHMETIC_URL ='/arithmetic/'
ARITHMETIC_DIRS=[
	os.path.join(BASE_DIR,'arithmetic')
]

# 163邮件的配置，需要163邮箱去配合
# 邮件配置
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 465
# 发送邮件的邮箱
EMAIL_HOST_USER = "所用邮箱类型的邮箱"
# 邮箱授权密码
EMAIL_HOST_PASSWORD = "邮箱密码"
# 收件人看到的发件人
EMAIL_FROM = "发件人名<所用邮箱类型的邮箱>"
# 启用ssh加密：
EMAIL_USE_SSL = True



# 富文本
TINYMCE_DEFAULT_CONFIG = {
	'theme': 'advanced',
	'width': 600,
	'height': 500,
}




# 设置redis缓存
CACHES = {
	"default": {
		# "BACKEND": "redis_cache.cache.RedisCache",
		"TIMEOUT": 300,
		"LOCATION": "39.96.13.213:6379",
		"OPTIONS": {
			"PASSWORD": "199652"
		}
	}
}
