# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-08 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('circles', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'circles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('sex', models.BooleanField(default=True)),
                ('sign', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=40, null=True)),
                ('img', models.CharField(max_length=400, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.User'),
        ),
    ]
